#ifndef __ERROR_H__
#define __ERROR_H__

#define ERRORCODE_NOERRORS 0
#define ERRORCODE_SIZE_DONT_MATCH 1
#define ERRORCODE_CANT_MALLOC 2
#define ERRORCODE_PARSER_ERROR 3
#define ERRORCODE_CANT_FILE_OPEN 4 
#define ERRORCODE_READFILE_NOERRORS 0
#define ERRORCODE_MPI_ERROR 5

#define ERRORCODE_CANT_READ_DATA 6

#endif

